# cfgInit.py
# Resolve config_temp.yml placeholders and write a project config.yml

import sys
from pathlib import Path

import yaml


# Keys containing {placeholder} references to sibling keys.
# Resolved in order so models_dir is available when sub-dirs reference it.
_PLACEHOLDER_KEYS = [
	"models_dir",
	"drd_exe",
	"simplex_model_dir",
	"mods_model_dir",
	"output_directory",
]

# Keys whose resolved values are converted to absolute paths.
_ABS_PATH_KEYS = {
	"models_dir",
	"drd_exe",
	"simplex_model_dir",
	"mods_model_dir",
	"output_directory",
	"hpc_outdir",
}


def _resolve_placeholders(cfg: dict) -> dict:
	"""Substitute {key} placeholders in string values using sibling keys."""
	resolved = dict(cfg)
	str_ctx = {k: v for k, v in resolved.items() if isinstance(v, str)}
	for key in _PLACEHOLDER_KEYS:
		if key not in resolved or not isinstance(resolved[key], str):
			continue
		try:
			resolved[key] = resolved[key].format(**str_ctx)
			str_ctx[key] = resolved[key]   # update context for later keys
		except KeyError as e:
			sys.exit(f"[cfg-init] Error: '{key}' references undefined placeholder {e}.")
	return resolved


def _to_abs(cfg: dict) -> dict:
	"""Convert path keys to absolute paths."""
	result = dict(cfg)
	for key in _ABS_PATH_KEYS:
		if key in result and isinstance(result[key], str):
			result[key] = str(Path(result[key]).resolve())
	return result


def run(args):
	"""Execute cfg-init logic given parsed args namespace."""
	# CWD guard: all path resolution assumes the project root is the working directory.
	if not Path("cfg/config_temp.yml").exists():
		print(
			"[cfg-init] Warning: 'cfg/config_temp.yml' not found relative to the current "
			"working directory. All dorado-run subcommands must be run from the project "
			"root for path resolution to work correctly.",
			file=sys.stderr,
		)

	template_path = Path(args.template).resolve()
	input_dir     = Path(args.input_dir).resolve()
	output_path   = Path(args.output).resolve()

	# Guard: never overwrite the template
	if output_path == template_path:
		sys.exit("[cfg-init] Error: --output must not be the same file as --template.")

	# Load template
	if not template_path.exists():
		sys.exit(f"[cfg-init] Error: Template not found: {template_path}")
	with open(template_path, "r", encoding="utf-8") as fh:
		cfg = yaml.safe_load(fh) or {}

	# Resolve internal placeholder cross-references, then absolutize paths
	cfg = _resolve_placeholders(cfg)
	cfg = _to_abs(cfg)

	# Scan input dir for pod5 symlink dirs
	if not input_dir.exists():
		sys.exit(f"[cfg-init] Error: Input directory does not exist: {input_dir}")

	pod5_dirs = sorted([
		str(p.resolve())
		for p in sorted(input_dir.iterdir())
		if p.is_dir()
	])

	if not pod5_dirs:
		print(f"[cfg-init] Warning: No entries found in {input_dir}. "
		      "pod5_dirs will be empty.", file=sys.stderr)

	cfg["pod5_dirs"] = pod5_dirs

	# Write resolved config with a header comment
	output_path.parent.mkdir(parents=True, exist_ok=True)
	with open(output_path, "w", encoding="utf-8") as fh:
		fh.write(
			"# Auto-generated by cfg-init. Do not edit this file directly.\n"
			"# Edit cfg/config_temp.yml and re-run 'dorado-run cfg-init'.\n\n"
		)
		yaml.dump(cfg, fh, default_flow_style=False, sort_keys=False, allow_unicode=True)

	print(f"[cfg-init] Wrote resolved config → {output_path}  ({len(pod5_dirs)} pod5 dir(s))")

